### ISSUE TITLE
EnhancedCaves plugin still shows verydangeroushelp message when doing /ec help

### ISSUE THREAD

**Issue by ValMobile** [mVabo/VeryDangerousCaves#7]
As the title says, when doing /ec help, the help message shows the verydangeroushelp message instead of the enhancedcaves help message. 
![image](https://user-images.githubusercontent.com/58125835/98471817-783c9c00-21b4-11eb-8f69-6dcabcf3884b.png)

**Comment by mVabo** [comment]
Fixed in next patch
