### ISSUE TITLE
Doing /ec spawn with no third argument creates an internal error

### ISSUE THREAD

**Issue by ValMobile** [mVabo/VeryDangerousCaves#9]
Doing /ec spawn with no third argument creates an internal error. What should happen is that the plugin prints a statement in chat that tells the user how to use the spawn command, provided they have the correct permission.
![image](https://user-images.githubusercontent.com/58125835/98471883-e6815e80-21b4-11eb-8a7f-0e3ea59d35ba.png)

**Comment by mVabo** [comment]
Possible fix added in next patch, please re-open if issue still appears.
